// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeIr-p__KF-KsuGKJ1sFHKKrN0GpXKxIc',
    appId: '1:853833082660:web:0ec9f6b8d7c96a36a235b1',
    messagingSenderId: '853833082660',
    projectId: 'm2iexcerciseletschat',
    authDomain: 'm2iexcerciseletschat.firebaseapp.com',
    storageBucket: 'm2iexcerciseletschat.firebasestorage.app',
    measurementId: 'G-W7QPGM2GGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-Yyld0nRpfm04fcuCf_5etJjdeyWRjo',
    appId: '1:853833082660:android:4d176352f0237d7fa235b1',
    messagingSenderId: '853833082660',
    projectId: 'm2iexcerciseletschat',
    storageBucket: 'm2iexcerciseletschat.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeIr-p__KF-KsuGKJ1sFHKKrN0GpXKxIc',
    appId: '1:853833082660:web:a71da7fad4e01e1ba235b1',
    messagingSenderId: '853833082660',
    projectId: 'm2iexcerciseletschat',
    authDomain: 'm2iexcerciseletschat.firebaseapp.com',
    storageBucket: 'm2iexcerciseletschat.firebasestorage.app',
    measurementId: 'G-V8STTZRMMZ',
  );
}
